# Generated by Django 2.2.3 on 2019-08-13 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190812_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 13, 11, 39, 56, 147625), verbose_name='date published'),
        ),
    ]
